group: Tests
depends_on: 
  - image-build
steps:
- label: "Simple Unit Test"
  commands:
    - ".buildkite/scripts/simple_test.sh"
  no_gpu: true

- label: "Diffusion Model Test"
  timeout_in_minutes: 15
  commands:
    - pytest -s -v tests/single_stage/test_diffusion_model.py

- label: "Omni Model Test"
  timeout_in_minutes: 15
  gpu: h100
  commands:
    - export VLLM_LOGGING_LEVEL=DEBUG
    - export VLLM_WORKER_MULTIPROC_METHOD=spawn
    - pytest -s -v tests/multi_stages/

- label: "Omni Model Test with H100"
  timeout_in_minutes: 20
  gpu: h100
  commands:
    - export VLLM_WORKER_MULTIPROC_METHOD=spawn
    - pytest -s -v tests/multi_stages_h100/